plugin: azure_rm
include_vm_resource_groups:
- e360vdilabs2
auth_source: msi
 
keyed_groups:
- prefix: mytestgroup
  key: tags.ServerRole | default('none')

exclude_host_filters:
- powerstate != 'running'
