---
# Run Packer build to prepare VDI image

- hosts: localhost
  become: yes
  vars:
    packerProjectPath: "/opt/packer/vdi"
    NetworkResourceGroupName: "E360VDILABS2"
    BuildResourceGroupName: "E360VDILABS2"
    ImageResourceGroupName: "E360VDILABS2"
    virtualNetworkName: "Citrix-Vnet"
    subnet0Name: "VirtualDesktops"
    VDIVMSize: "Standard_D2_v2"

  tasks: 

    - name: " Create Packer execution directory "
      file:
        path: "{{ packerProjectPath }}"
        group: adm
        mode: '775'
        state: directory

    - name: " Convert Powershell scripts from jinja2 template "
      template:
        src: ../templates/vdi_build.j2
        dest: "{{ packerProjectPath }}/vdi_build.json"

    - name: " Copy vdi scripts to {{ packerProjectPath }} "
      copy:
        src: ../scripts/{{ item }}
        dest: "{{ packerProjectPath }}/scripts/"
      with_items:
      - baseline_features.ps1
      - baseline_svc.ps1
      - installs.ps1
      - vda.ps1
      - vdi.ps1

    - name: " Packer build "
      command: /usr/local/bin/packer build vdi_build.json
      args:
        chdir: "{{ packerProjectPath }}/"

...

