---
# Run Packer build to prepare VDI image

- hosts: localhost

  tasks: 
    - include_vars: ../inventory/hosts.yaml
    - name: " Convert Powershell scripts from jinja2 template "
      template:
        src: ../templates/vdi_build.j2
        dest: ../scripts/vdi_build.json

 #   - name: " Packer build "
 #     command: packer build ../scripts/vdi_build.json

...

