---

- hosts: 'entisyscc1'

  tasks:
      # This will convert all Powershell scripts

    - name: "Convert powershell scripts from jinja2 template"
      template:
        src: '../templates/Machine_catalog.j2'
        dest: 'c:\Machine_catalog.ps1'

        # Running Script 2: Machine_catalog.ps1
    - name: "Machine_catalog.ps1"
      win_shell: c:\Machine_catalog.ps1 >> C:\somelog.txt
