---

- hosts: e360CCprimary
  become: yes

  tasks:
      # This will convert all Powershell scripts from /templates folder into Powershell scripts and move them to /scripts folder
    - name: "Convert powershell scripts from jinja2 template"
      template:
        src: ../templates/{{ item.j2 }}
        dest: c:\{{ item.posh }}
      loop:
        - { j2: 'Connect-AztoCitrixHostConnection.j2', posh: 'Connect-AztoCitrixHostConnection.ps1' }
        - { j2: 'Machine_catalog.j2', posh: 'Machine_catalog.ps1' }
        - { j2: 'DeliveryGroup.j2', posh: 'DeliveryGroup.ps1' }

      # Running Script 1: Connect-AztoCitrixHostConnection.ps1
    - name: "Connect-AztoCitrixHostConnection.ps1" 
      ansible.windows.win_shell: c:\Connect-AztoCitrixHostConnection.ps1 >> C:\somelog.txt

      # Running Script 2: Machine_catalog.ps1
    - name: "Machine_catalog.ps1"
      ansible.windows.win_shell: c:\Machine_catalog.ps1 >> C:\somelog.txt

      # Running Script 3:.ps1
    - name: "DeliveryGroup.ps1"
      ansible.windows.win_shell: c:\DeliveryGroup.ps1 >> C:\somelog.txt
    
...

